Restaurant.create(name: "Epicure", address: "75008 Paris", phone_number: "0123456789", category: "french")
Restaurant.create(name: "Sushi Zen", address: "Tokyo, Japan", phone_number: "0987654321", category: "japanese")
Restaurant.create(name: "Pasta Palace", address: "Rome, Italy", phone_number: "0112233445", category: "italian")
Restaurant.create(name: "Waffle Heaven", address: "Brussels, Belgium", phone_number: "0223344556", category: "belgian")
Restaurant.create(name: "Dim Sum House", address: "Beijing, China", phone_number: "0334455667", category: "chinese")
